### ISSUE TITLE
Does this require middle layer stuff for authentication?

### ISSUE THREAD

**Issue by lmatteis** [max-mapper/datacouch#16]
Will this work as a standalone couchapp or does it require a middle layer (node.js) to serve some requests for Twitter authentication and other things?

**Comment by max-mapper** [comment]
twitter auth code: https://github.com/maxogden/datacouch/tree/master/processors/auth
uses couch's built in http basic auth too, and the couch built in http proxy. the whole thing is served from couch but it uses couch's http proxy to make auth requests to a node server. that way i could still write flexible auth (e.g. not erlang plugins) but still expose couch to the end user so they can replicate their data
i use the crypto module to set the password to a random string, then store that in the users doc. so the users db has to be private for the security model to make sense. im just using the _security object to make the users db not accessible to non admins
