### ISSUE TITLE
Delete all documents only deletes some documents

### ISSUE THREAD

**Issue by peterk** [max-mapper/datacouch#18]
If I try to delete all documents in a dataset (e.g. if the CSV import format was wrong) only some documents are deleted (approx 1500 per run). The dataset I tried to empty had ~9000 documents to start with.

**Comment by max-mapper** [comment]
thanks for the bug report. on my to-do list is a rewrite of this feature where all the data will be transformed on the server side so it will be a lot faster and less dependent on web browser performance (all the data transformations take place on the client side currently)

what browser version were you using?

**Comment by peterk** [comment]
Sounds excellent. Google Chrome 15.0.874.121 Mac OS X.

**Comment by max-mapper** [comment]
this should be fixed now. I will do more QA to be sure though
