### ISSUE TITLE
npm install does not catch jsonparse module

### ISSUE THREAD

**Issue by cole-gillespie** [max-mapper/datacouch#26]
I started with a fresh clone of your latest node_server branch 

Steps to replicate:
1. git checkout -b node_server_dev upstream/node_server
2. node run.
3. npm install ( to get csv )
4. node run ( npm install does not catch jsonparse )
5. npm install ( nothing but a underscore warning )
6. node run ( fail )

would it be best to add json parse to node_server branch to prevent this from happening to other in the future??

Log listed below
# 

Coles-MacBook-Air:datacouch cole$ node run
The "sys" module is now called "util". It should have a similar interface.

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: Cannot find module 'csv'
    at Function._resolveFilename (module.js:334:11)
    at Function._load (module.js:279:25)
    at Module.require (module.js:357:17)
    at require (module.js:368:17)
    at Object.<anonymous> (/Users/cole/Public/github/datacouch/service/csv_uploader.js:2:11)
    at Module._compile (module.js:432:26)
    at Object..js (module.js:450:10)
    at Module.load (module.js:351:31)
    at Function._load (module.js:310:12)
    at Module.require (module.js:357:17)

Coles-MacBook-Air:datacouch cole$ npm install
npm WARN underscore@1.2.1 dependencies field should be hash of <name>:<version-range> pairs
npm http GET https://registry.npmjs.org/csv/0.0.10
npm http GET https://registry.npmjs.org/couchapp/0.8.1
npm http 304 https://registry.npmjs.org/couchapp/0.8.1
npm http 304 https://registry.npmjs.org/csv/0.0.10
couchapp@0.8.1 ./node_modules/couchapp 
csv@0.0.10 ./node_modules/csv 

Coles-MacBook-Air:datacouch cole$ node run
The "sys" module is now called "util". It should have a similar interface.

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: Cannot find module 'jsonparse'
    at Function._resolveFilename (module.js:334:11)
    at Function._load (module.js:279:25)
    at Module.require (module.js:357:17)
    at require (module.js:368:17)
    at Object.<anonymous> (/Users/cole/Public/github/datacouch/node_modules/JSONStream/index.js:2:14)
    at Module._compile (module.js:432:26)
    at Object..js (module.js:450:10)
    at Module.load (module.js:351:31)
    at Function._load (module.js:310:12)
    at Module.require (module.js:357:17)

Coles-MacBook-Air:datacouch cole$ npm install
npm WARN underscore@1.2.1 dependencies field should be hash of <name>:<version-range> pairs

Coles-MacBook-Air:datacouch cole$ node run
The "sys" module is now called "util". It should have a similar interface.

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: Cannot find module 'jsonparse'

**Comment by max-mapper** [comment]
in the log output above the first time you ran npm install it only installed csv and couchapp. the most recent version of package.json has more modules than that: https://github.com/maxogden/datacouch/blob/node_server/package.json

are you sure it was a complete fresh clone of the HEAD of the node_server branch?

**Comment by cole-gillespie** [comment]
that is a good point. i thought that is what i was doing when i ran

git checkout -b node_server_dev upstream/node_server

but i think it only did csv because npm was smart enough to see that I already had some of the other modules installed before hand. let me run npm install from a brand new clone and see what happens.

**Comment by cole-gillespie** [comment]
brand new clone install output

Coles-MacBook-Air:datacouch cole$ npm install
npm WARN underscore@1.2.1 dependencies field should be hash of <name>:<version-range> pairs
npm http GET https://registry.npmjs.org/couchapp/0.8.1
npm http GET https://registry.npmjs.org/csv/0.0.10
npm http 304 https://registry.npmjs.org/csv/0.0.10
npm http 304 https://registry.npmjs.org/couchapp/0.8.1
couchapp@0.8.1 ./node_modules/couchapp 
csv@0.0.10 ./node_modules/csv 
Coles-MacBook-Air:datacouch cole$ node run
The "sys" module is now called "util". It should have a similar interface.

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: Cannot find module 'jsonparse'
    at Function._resolveFilename (module.js:334:11)
    at Function._load (module.js:279:25)
    at Module.require (module.js:357:17)
    at require (module.js:368:17)
    at Object.<anonymous> (/Users/cole/Public/datacouch/node_modules/JSONStream/index.js:2:14)
    at Module._compile (module.js:432:26)
    at Object..js (module.js:450:10)
    at Module.load (module.js:351:31)
    at Function._load (module.js:310:12)
    at Module.require (module.js:357:17)

**Comment by cole-gillespie** [comment]
that does not seem right...

**Comment by dominictarr** [comment]
can you paste in `npm ls` after the install?

hmm, it appears that this my be related to JSONStream, which seems odd. does it work if you install JSONStream directly?

**Comment by max-mapper** [comment]
@dominictarr the issue was that you checked in your `.gitignore` with JSONStream and then when I checked in JSONStream it didn't include the `node_modules` inside, so when @coleGillespie did `npm install` his `npm` saw that he already had JSONStream in `node_modules` and skipped installation, but `npm` didn't realize that JSONStream was missing a dependency.

**Comment by dominictarr** [comment]
okay, but I want the .gitignore in my repo because I don't want node_modules in my reusable lib's repo.

but you want it in your deployable app here, so feels like a catch 22. 
I could use a global .gitignore, but that would mess up my apps. 

so what is the solution here?

an .npmignore that ignores .gitignore?

**Comment by cole-gillespie** [comment]
You could always just add your node_modules later once you delete the node_modules dir and your .gitignore and leave them untracked by git ya know. Just do not "git add" them.

**Comment by dominictarr** [comment]
oh, all I need to do is republish JSONStream

https://github.com/isaacs/npm/issues/1862

npm now automatically uses .gitignore as npm ignore.

**Comment by dominictarr** [comment]
okay, just published JSONStream 1.1.3

try that.

**Comment by max-mapper** [comment]
jsonstream 0.1.3 successfully installs jsonparse
