### ISSUE TITLE
Unauthorized token 

### ISSUE THREAD

**Issue by mef** [max-mapper/datacouch#31]
Hello,

I would like to use datacouch programatically, therefore load data using the couchdb API. However, whenever I click on the token link, the page keeps loading during minutes without returning anything. If I open the 'token' hyperlink in a new tab, I get 'Unauthorized' anwer.

Any solution? Did I do something wrong?

Using firefox (iceweasel) on Linux

**Comment by max-mapper** [comment]
Hi, sorry! I am working on rewriting datacouch in nodejs (https://github.com/maxogden/datacouch/tree/node_server) and am in the middle of upgrading. Keep an eye on this repo to see when the new version is released

**Comment by mef** [comment]
No problem, Thanks
