### ISSUE TITLE
polymapper loads eternally

### ISSUE THREAD

**Issue by neophiliac** [max-mapper/datacouch#9]
Imported a CSV with 98 rows, then clicked Applications and chose polymapper. Spinner is still spinning. Happens in surf (bare webkit browser) and Chrome 15.0.874.51 beta.

**Comment by neophiliac** [comment]
Same with boilerplate. Doesn't appear to be app-specific.

**Comment by max-mapper** [comment]
thanks for alpha testing! the boilerplate app should load a hello world page (http://c6e12196af8d11d583b147a7755fef3e.rectangl.es/)

right now `catmapper` should load up and let you save locations. once there are locations (documents with a `geometry` property that contain GeoJSON values) in your dataset then they should show up in `polymapper`
